### ISSUE TITLE
`Cannot assign requested address` on `php7`

### ISSUE THREAD

**Issue by yinshanyang** [lagun4ik/dockerizedVestaCP#2]
When I spin up a container with `docker run --rm --volume vesta:/vesta -p 2222:22 -p 80:80 -p 8083:8083 -p 3306:3306 -p 443:443 -p 25:25 -p 993:993 -p 110:110  -p 53:53 -p 54:54 lagun4ik/vestacp:php7` I get the following error

```
nginx: [emerg] bind() to 172.17.0.3:80 failed (99: Cannot assign requested address)
*** /etc/my_init.d/startup.sh failed with status 1
```

The image works fine for `:latest`, just fails with `:php7`. Could it be related to the following part of the `Dockerfile`?

```
RUN bash /install-ubuntu.sh \
 --password admin \
 -y no -f \
 && apt-get clean
```

**Comment by peerasan** [comment]
Also face the issue. The issue still not fix yet?

**Comment by lagun4ik** [comment]
Likely fixed, test please
