### ISSUE TITLE
ERROR: The partition with /var/lib/mysql is too full!

### ISSUE THREAD

**Issue by pierrediancourt** [lagun4ik/dockerizedVestaCP#5]
If i run your docker image with 

`docker run --net=isolated_nw \
-p 22222:22 -p 80:80 -p 8083:8083 -p 443:443 -p 25:25 -p 993:993 -p 53:53 -p 53:53/udp \
--hostname=vesta -v /volumes/vesta:/vesta --name vesta -d lagun4ik/vestacp:php7`

The command works find and return me the unique id of the container.
So i want to verify if all is working and i check the logs with `docker logs vesta`
And I get this output 

"
**\* Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
**\* Running /etc/my_init.d/startup.sh...
  Starting vesta-nginx vesta-nginx
   ...done.
  Starting vesta-php vesta-php
   ...done.
df: '/var/lib/mysql/.': No such file or directory
  ./mysql: ERROR: The partition with /var/lib/mysql is too full!
**\* /etc/my_init.d/startup.sh failed with status 1

**\* Killing all processes...
"

As you can see i have plenty of space where i mount the volume 

"
df -h /volumes/vesta
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda9       901G   28G  836G   4% /
"

I didn't find any fix for now but maybe this thread will give you some hints to correct this bug
http://askubuntu.com/questions/482923/mysql-error-the-partition-with-var-lib-mysql-is-too-full

Thx for your work

**Comment by pierrediancourt** [comment]
Sorry to bother you again, but could you please fix the php7 branch too ? :)

Anyway i'm still facing the same error.
It's clearly still related to the "-v" clause when running the container as it runs fine when i remove it.
But not having access to the inner content of the container is not an option.

Thanks for you time

PS : i'm running on CoreOS stable
Docker version 1.10.3, build 1f8f545

**Comment by lagun4ik** [comment]
@pierrediancourt fix it in php7 branch. thanks
