### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by pierrediancourt** [lagun4ik/dockerizedVestaCP#7]
Hi,

When i run the command 

> docker run --net=isolated_nw \
> -p 2200:22 -p 80:80 -p 8083:8083 -p 443:443 \
> -v /volumes/vesta:/vesta \
> --hostname=vesta --name vesta \
> -d lagun4ik/vestacp:php7

I can't login as admin with password admin

I'm on a fresh debian 8 install with `Docker version 1.12.3, build 6b644ec`

**Comment by lagun4ik** [comment]
If the `/volumes/vesta` has the necessary data, run the command `chmod 775 /volumes/vesta/local/vesta/data/sessions/` and clear cookies

**Comment by pierrediancourt** [comment]
chmod 777 solved the issue, 775 didn't
Thanks a lot

**Comment by lagun4ik** [comment]
`/volumes/vesta/local/vesta/data/sessions` existed?
