### ISSUE TITLE
ngnix + phpfpm (NO mysql, and apache)

### ISSUE THREAD

**Issue by ja9adeesh** [lagun4ik/dockerizedVestaCP#8]
is it possible to create a branch with custom parameters
something like below, 

    --nginx yes --phpfpm yes --apache no 
    --vsftpd no --proftpd no 
    --exim yes --dovecot yes --spamassassin yes --clamav yes 
    --named yes 
    --iptables no --fail2ban no 
    --mysql no --postgresql no 
    --remi no 
    --quota no

i tried it by ediding `Dockerfile` with above params but failed to build docker image.

    Error: default backend template doesn't exist

**Comment by lagun4ik** [comment]
No.
You can do it yourself.
